Login_And_Registration/urls.py
from django.urls import path
from . import views

app_name = 'login'
urlpatterns = [
    path('', views.home, name = "home"),
    path('register/', views.register, name = "register"),
    path('login/', views.login, name = "login"),
    path('success/', views.success, name = "success"),
    path('logout/', views.logout, name = "logout"),
]

WallApp/urls.py
from django.urls import path
from . import views

app_name = 'wall'
urlpatterns = [
    path('', views.wall_home, name = 'wall_home'),
    path('addmsg/', views.add_message, name = 'add_message'),
    path('addcomment/<postid>', views.add_comment, name = 'add_comment'),
    path('delete/', views.delete_comment, name = 'delete_comment'),
    path('post/delete/', views.delete_post, name = 'delete_post'),
]

WeekSix/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('Login_And_Registration.urls')),
    path('wall/', include('WallApp.urls')),
]

Login_And_Registration/models.py
from django.db import models
import re, datetime
from datetime import date, datetime
from django.db.models.deletion import CASCADE

from django.db.models.fields import related

# Thanks, StackOverflow!
def calculate_age(born):
    today = date.today()
    return today.year - born.year - ((today.month, today.day) < (born.month, born.day))

class ValidationTest(models.Manager):
    def basic_validation(self, postData):
        errors = {}
        if len(postData['firstname']) < 2:
            errors['firstname'] = "First name must be more than two characters."
        if len(postData['lastname']) < 2:
            errors['lastname'] = "Last name must be more than two characters."
        EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
        if not EMAIL_REGEX.match(postData['email']):
            errors['email'] = "Invalid email address!"
        emaildupcheck = User.objects.filter(email=postData['email'])
        if emaildupcheck == postData['email']:
            errors['email'] = "email address already exists. Did you forget your password?"
        # Magic to make the date comparison work.
        dateentered = postData['birthdate']
        birthdate = datetime.strptime(dateentered, "%Y-%m-%d")
        today = datetime.now()
        if birthdate >= today:
            errors['birthdate'] = "You're not a time traveler. Your birthdate must be in the past."
        elif calculate_age(birthdate) < 13:
            errors['birthdate'] = "You must be at least 13 years old to sign up for this website."
        if len(postData['password']) < 8:
            errors['password'] = "Your password must be at least 8 characters."
        if not postData['confirm-pw'] == postData['password']:
            errors['confirm-pw'] = "Password mismatch. Maybe a typo? Please try again!"
        return errors

class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    birthdate = models.DateField()
    email = models.EmailField()
    password = models.CharField(max_length=255)
    
    objects = ValidationTest()

class WallPost(models.Model):
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(
        User,
        related_name = 'usr_post',
        on_delete = CASCADE,
    )

class Comments(models.Model):
    comment = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(
        User,
        related_name = 'user_comments',
        on_delete = CASCADE,
    )
    message = models.ForeignKey(
        WallPost,
        related_name = 'msg_comment',
        on_delete = CASCADE,
    )

WallApp/models.py
from django.db import models

# Create your models here.

Login_And_Registration/views.py
from WallApp.views import wall_home
from django.http.response import HttpResponse
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from .models import User
import bcrypt

def home(request):
    return render(request, 'html/home.html' )

def register(request):
    if request.method == 'POST':
        errors = User.objects.basic_validation(request.POST)
        if len(errors) > 0:
            for key, value in errors.items():
                messages.error(request, value, extra_tags='danger')
            return redirect('login:home')
        prehash = request.POST['password']
        hash_n_salt = bcrypt.hashpw(prehash.encode(), bcrypt.gensalt(17)).decode()
        newuser = User.objects.create(
            first_name = request.POST['firstname'], 
            last_name = request.POST['lastname'], 
            birthdate = request.POST['birthdate'],
            email = request.POST['email'],
            password = hash_n_salt
        )
        request.session['userid'] = newuser.id
        messages.success(request, f"User { request.POST['email'] } has been created successfully!")
        return redirect('login:success')
    else:
        return redirect('login:home')

def success(request):
    if request.method == 'POST':
        if request.session['userid']:
            context = {
                "userinfo" : User.objects.get(id = request.session['userid'])
            }
            return render(request, 'html/success.html', context)
    else:
        return redirect('login:home')

def logout(request):
    request.session.flush()
    request.session['loggedin'] = False
    return redirect('login:home')

def login(request):
    if request.method == 'POST':
        user = User.objects.filter(email = request.POST['email_login'])
        if user:
            loggedin_user = user[0]
            print("USER LOCATED")
            if bcrypt.checkpw(request.POST['password_login'].encode(), loggedin_user.password.encode()):
                print("PASSWORD VALIDATED")
                request.session['userid'] = loggedin_user.id
                request.session['loggedin'] = True
                print(request.session['userid'])
                messages.success(request, f"User {loggedin_user.first_name} has logged in!")
                context = {
                    'loggedin_user': loggedin_user
                }
                return redirect('wall:wall_home')
    else:
        return redirect('login:home')

WallApp/views.py
from django.shortcuts import render, redirect, HttpResponse
from Login_And_Registration.models import User, WallPost, Comments
from django.contrib import messages

def wall_home(request):
    if request.session['loggedin'] == False:
        messages.error(request, f"You must be logged in to post to the wall.", extra_tags='danger')
        return redirect('login:home')
    context = {
        'wallposts': WallPost.objects.all(),
        'comments': Comments.objects.all(),
        'loggedinuser': User.objects.get(id = request.session['userid'])
        }
    return render(request, 'wallapp/wall.html', context)
        

def add_message(request):
    if request.method == 'POST':
        posting_user = User.objects.get(id = request.session['userid'])
        new_message = WallPost.objects.create(
            message = request.POST['message'],
            user = posting_user,
        )
        return redirect('wall:wall_home')
    else:
        return redirect('wall:wall_home')

def add_comment(request, postid):
    if request.method == 'POST':
        posting_user = User.objects.get(id = request.session['userid'])
        wall_post = WallPost.objects.get(id = postid)
        new_comment = Comments.objects.create(
            comment = request.POST['comment'],
            user = posting_user,
            message = wall_post,
        )
        return redirect('wall:wall_home')
    else:
        return redirect('wall:wall_home')

def delete_post(request):
    if request.method == 'POST':
        post_to_kill = WallPost.objects.get(id = request.POST['commentid'])
        post_to_kill.delete()
        return redirect('wall:wall_home')
    else:
        return redirect('wall:wall_home')

def delete_comment(request):
    if request.method == 'POST':
        comment_to_kill = Comments.objects.get(id = request.POST['commentid'])
        comment_to_kill.delete()
        return redirect('wall:wall_home')
    else:
        return redirect('wall:wall_home')

Login_And_Registration/templates/html/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% if pagetitle %}
    <title>{{ pagetitle }}</title>
    {% else %}
    <title>Login & Registration</title>
    {% endif %}
</head>
<body>
    <div class="container rounded-lg shadow bg-gradient-light text-dark">
        <nav class="navbar navbar-dark bg-dark justify-content-between mt-2 mb-5">
            <a class="navbar-brand" href="#">Coding Dojo Wall</a>
            {% if loggedin_user %}
            <p class="text-light">Welcome {{loggedin_user.first_name}}! | <a href="{% url 'login:logout' %}">Log Out</a></p>
            {% else %}
            <p class="text-light">Please, <a href="{% url 'login:login' %}">Log In</a></p>
            {% endif %}
        </nav>
        <div class="row align-items-start justify-content-start mb-2">
            <div class="col align-self-start">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        {% block content %}
        {% endblock content %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

Login_And_Registration/templates/html/home.html
{% extends "html/base.html" %}
{% block content %}
<div class="row justify-content-around">
    <div class="col-6 mb-2 text-center">
        <h2>Registration</h2>
    </div>
    <div class="col-6 mb-2 text-center">
        <h2>Log In</h2>
    </div>
</div>
<div class="row align-items-start justify-content-around pr-5 pl-5">
    <div class="col-6 align-self-start">
        <form action="{% url 'login:register' %}" method="POST">
            {% csrf_token %}
            <div class="form-group row">
                <label for="firstname" class="col-3 col-form-label">First Name</label>
                <div class="col">
                    <input class="form-control" type="text" name="firstname" id="firstname">
                </div>
            </div>
            <div class="form-group row">
                <label for="lastname" class="col-3 col-form-label">Last Name</label>
                <div class="col">
                    <input class="form-control" type="text" name="lastname" id="lastname">
                </div>
            </div>
            <div class="form-group row">
                <label for="birthdate" class="col-3 col-form-label">Birthdate</label>
                <div class="col">
                    <input class="form-control" type="date" name="birthdate" id="birthdate">
                </div>
            </div>
            <div class="form-group row">
                <label for="email" class="col-3 col-form-label">email</label>
                <div class="col">
                    <input class="form-control" type="email" name="email" id="email">
                </div>
            </div>
            <div class="form-group row">
                <label for="password" class="col-3 col-form-label">Password</label>
                <div class="col">
                    <input class="form-control" type="password" name="password" id="password">
                </div>
            </div>
            <div class="form-group row">
                <label for="confirm-pw" class="col-3 col-form-label">Confirm Password</label>
                <div class="col">
                    <input class="form-control" type="password" name="confirm-pw" id="confirm-pw">
                </div>
            </div>
            <div class="col text-center mb-5">
                <button type="submit" class="btn btn-primary">Register</button>
            </div>
        </form>
    </div>
    <div class="col-6 align-self-start">
        <form action="{% url 'login:login' %}" method="POST">
            {% csrf_token %}
            <div class="form-group row">
                <label for="email_login" class="col-3 col-form-label">email</label>
                <div class="col">
                    <input class="form-control" type="email" name="email_login" id="email_login">
                </div>
            </div>
            <div class="form-group row">
                <label for="password_login" class="col-3 col-form-label">Password</label>
                <div class="col">
                    <input class="form-control" type="password" name="password_login" id="password_login">
                </div>
            </div>
            <div class="col text-center mb-5">
                <button type="submit" class="btn btn-primary">Log In</button>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

Login_And_Registration/templates/html/success.html
{% extends "html/base.html" %}
{% block content %}
<div class="row">
    <div class="col-11 mb-2 mt-2">
        <h2>Success! Welcome {{ userinfo.first_name }}</h2>
        <p class="text-success">Successfully logged in or registered!</p>
    </div>
    <div class="col-1 mb-2 mt-2">
        <small><a href="{% url 'logout' %}">Log Out</a></small>
    </div>
</div>
{% endblock content %}

WallApp/templates/wallapp/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    {% if pagetitle %}
    <title>{{ pagetitle }}</title>
    {% else %}
    <title>Coding Dojo Wall Application</title>
    {% endif %}
</head>
<body>
    <div class="container rounded-lg shadow bg-gradient-light text-dark pt-1 pb-5">
        <nav class="navbar navbar-dark bg-dark justify-content-between mb-5">
            <a class="navbar-brand" href="#">Coding Dojo Wall</a>
            {% if loggedinuser %}
            <p class="text-light">Welcome {{ loggedinuser.first_name }}! | <a href="{% url 'login:logout' %}">Log Out</a></p>
            {% else %}
            <p class="text-light">Please, log in! | <a href="{% url 'login:login' %}">Log In</a></p>
            {% endif %}
        </nav>
        <div class="row align-items-start justify-content-start mb-2">
            <div class="col align-self-start">
                {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </div>
        {% block wall %}
        {% endblock wall %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>
</html>

WallApp/templates/wallapp/wall.html
{% extends "wallapp/base.html" %}
{% block wall %}
<form action="{% url 'wall:add_message' %}" method="POST">
    {% csrf_token %}
    <div class="form-group">
        <label for="message">Post A Message!</label>
        <textarea class="form-control" name="message" id="message" rows="5"></textarea>
    </div>
    <div class="text-right mb-3">
        <button type="submit" class="btn btn-primary">Post Message</button>
    </div>
</form>
{% if wallposts %}
{% for post in wallposts %}
<div class="row">
    <div class="col-auto ml-5">
        <p class="font-weight-bold">{{ post.user.first_name }} {{ post.user.last_name }} - {{ post.created_at|date:"F j, Y" }}</p>
    </div>
</div>
<div class="row align-items-end">
    <div class="col-1"></div>
    <div class="col-10">
        <p class="text-right">{{ post.message }}</p>
    </div>
    {% if post.user.id == loggedinuser.id %}
    <div class="col-1 align-self-center">
        <form action="{% url 'wall:delete_post' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="postid" value="{{ post.id }}">
            <button type="submit" class="btn btn-danger">DELETE</button>
        </form>
    </div>
    {% endif %}
</div>
{% if comments %}
{% for comment in comments %}
{% if comment.message.id == post.id %}
<div class="row">
    <div class="col-auto ml-5 pl-5">
        <p class="font-weight-bold">{{ comment.user.first_name }} {{ comment.user.last_name }} - {{ comment.created_at|date:"F j, Y" }}</p>
    </div>
</div>
<div class="row align-items-end">
    <div class="col-1"></div>
    <div class="col-10">
        <p class="text-right">{{ comment.comment }}</p>
    </div>
    {% if comment.user.id == loggedinuser.id %}
    <div class="col-1 align-self-center">
        <form action="{% url 'wall:delete_comment' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="commentid" value="{{ comment.id }}">
            <button type="submit" class="btn btn-danger">DELETE</button>
        </form>
    </div>
    {% endif %}
</div>
<!-- End Comment Block. -->
{% endif %}
{% endfor %}
{% endif %}
<div class="row align-items-end">
    <div class="col-2"></div>
    <div class="col-10">
        <form action="{% url 'wall:add_comment' post.id %}" method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="comment">Post A Comment!</label>
                <textarea class="form-control" name="comment" id="comment" rows="3"></textarea>
            </div>
            <div class="text-right mb-3">
                <button type="submit" class="btn btn-success">Post Comment</button>
            </div>
        </form>
    </div>
</div>
<!-- End Message Block. -->
{% endfor %}
{% endif %}
<!-- End Page. -->
{% endblock wall %}